### ISSUE TITLE
App.yaml config for Google App Engine.

### ISSUE THREAD

**Issue by Pixelatex** [nozzle/react-static#802]
**Describe the bug**
When deploying the site to an app engine, the yaml file doesn't seem to function as intended. You need to do /path/index.html for it to work.

!The internal router does work but refreshing or direct to url navigation will break it!

**To Reproduce**
Deploy a site on a google app engine and see what the routing does.

**Expected behavior**
The routes should work as normal.

**Possible fix**
The app.yaml may require a different config that can be triggered with a parameter in the static.config?

**Comment by tannerlinsley** [comment]
Even outside of React-Static I have had issues with GAE and static sites. To me, this issue sounds like a GAE config routing issue. I can't remember how to do it, but you need to make the `dist/index.html` file the default file for html5 mode.

Does this help? Seems like I would start here: https://cloud.google.com/appengine/docs/standard/php/getting-started/hosting-a-static-website

**Comment by Pixelatex** [comment]
The strange thing is:

```
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

#- url: /(.*)
#  static_files: \1
#  upload: (.*)

# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: \1/index.html
  upload: .*/index.html

# Handle nearly every other file by just serving it.
- url: /(.+)
  static_files: \1
  upload: (.*)

```

This will work, css files and such are served... however, it refuses to server the index.html files inside a folder on refresh or direct navigation via url

**Comment by tannerlinsley** [comment]
Does this not work?

```
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
```

Honestly, I think this is what drove us to use S3 + cloudfront (where we ran into similar issues), then finally Netlify (where we have been overjoyed since).

**Comment by Pixelatex** [comment]
Nah, that breaks it completely. There is not dist folder as the app.yaml is inside the dist folder...

Really annoyed that I can't get this working... :/ what a mess.

**Comment by tannerlinsley** [comment]
Hmmm. It could have something to do with trailing/non-trailing slashes...

**Comment by Pixelatex** [comment]
I can get everything working but the subfolder completely screws it somehow.. :/

**Comment by Pixelatex** [comment]
```
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(gif|png|jpg|css|js|json))$
  static_files: \1
  upload: (.*)

- url: /(.*)
  static_files: \1/index.html
  upload: .*/index.html
```

This seems to work now! holy damn... what a mess.

It seems you need to do a /*url* that will redirect to *url*/index.html.
And all static files need their own yaml handler to prevent them from interfering. I'll test this a bit more and maybe add it to the docs?
