### ISSUE TITLE
Empty instead of remove dist folder

### ISSUE THREAD

**Issue by airtonix** [nozzle/react-static#836]
**Is your feature request related to a problem? Please describe.**

I use docker in local and production

```sh
$ react-static build 
  Error: EBUSY: resource busy or locked, rmdir '/app/dist'
```
Simple example, fully available here: https://github.com/airtonix/zenobi.us/tree/feature/react-static

this is my docker-compose:

```yml
version: "2.0"

services:

  tool:
    image: ${npm_package_docker_image}:${npm_package_docker_tag}
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=config*
    volumes:
      - "./src:/app/src"
      - "./dist:/app/dist"
      - "./config:/app/config"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"
```

I don't do my mounts like this because it's slow (before executing anything on startup the container has to copy node_modules back up from the previous layer).
```yml
volumes:
  - "./:/app"
  - "/app/node_modules"
```

**Describe the solution you'd like**
use `del` to glob remove all files within the dist folder.
https://github.com/nozzle/react-static/blob/master/src/commands/bundle.js#L46

```js
import del from 'del';
del.sync([`${config.paths.DIST}/**/*`]);
```
